server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: ${EUREKA_NAME}.eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka
